<h1 class="ui header">Arquivos</h1>
<div class="ui grid">
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card">
			<div class="content">
				<div class="header">Lista 1.pdf</div>
			</div>
			<div class="content">
				<h4 class="ui sub header">Matemática</h4>
				<div class="ui small feed">
					<div class="event">
						<div class="content">
							<div class="summary">
								Material enviado para resolução de questões
							</div>
							<div class="extra">
								Adicionado por <a>Lucas</a> 
								dia 24 de abril, 2018
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="extra content">
				<button class="ui button">Download</button>
			</div>
		</div>
	</div>
</div>