<div class="ui top attached tabular menu">
  <a class="item active" data-tab="first">ProENEM</a>
  <a class="item" data-tab="second">ProRedação</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="first">
	<div class="ui styled fluid accordion">
		<div class="title">
			<i class="dropdown icon"></i>
			Matemática
		</div>
		<div class="content">
			
	  </div>
	  <div class="title">
	    <i class="dropdown icon"></i>
	    Português
	  </div>
	  <div class="content">
	    
	  </div>
	  <div class="title">
	    <i class="dropdown icon"></i>
	    Biologia
	  </div>
	  <div class="content">
	    
	  </div>
	  <div class="title">
	    <i class="dropdown icon"></i>
	    Química
	  </div>
	  <div class="content">
	    
	  </div>

	<div class="title">
	    <i class="dropdown icon"></i>
	    Física
	  </div>
	  <div class="content">
	    
	  </div>
	
	<div class="title">
	    <i class="dropdown icon"></i>
	    Filosofia
	  </div>
	  <div class="content">
	    
	  </div>

	<div class="title">
	    <i class="dropdown icon"></i>
	    Geografia
	  </div>
	  <div class="content">
	    
	  </div>

	<div class="title">
	    <i class="dropdown icon"></i>
	    História
	  </div>
	  <div class="content">
	    
	  </div>

	<div class="title">
	    <i class="dropdown icon"></i>
	    Sociologia
	  </div>
	  <div class="content">
	    
	  </div>

	</div>
</div>
	
	

<div class="ui bottom attached tab segment" data-tab="second">
  <div class="ui styled fluid accordion">
		<div class="title">
			<i class="dropdown icon"></i>
			Matemática
		</div>
		<div class="content">
			<table class="ui celled striped table transition hidden">
			  <thead>
			    <tr><th>
			      Arquivo
			    </th><th>
			      Descrição
			    </th>
			  </tr></thead>
			  <tbody>
			    <tr>
			      <td class="collapsing">
			        <i class="file outline  icon"></i> node_modules
			      </td>
			      <td>Initial commit</td>
			      <td class="right aligned collapsing"><a class="item" href="">Download</a></td>
			    </tr>
			  </tbody>
			</table>
	  </div>
	  <div class="title">
	    <i class="dropdown icon"></i>
	    Português
	  </div>
	  <div class="content">
	    <p>There are many breeds of dogs. Each breed varies in size and temperament. Owners often select a breed of dog that they find to be compatible with their own lifestyle and desires from a companion.</p>
	  </div>
</div>