<h1 class="ui header">Postagens Recentes</h1>
<div class="ui divided items">
	<div class="item">
		<a class="ui tiny image">
			<img src="static/images/avatar/jenny.jpg">
		</a>
		<div class="content">
			<a class="header" href=""><h2>Inscrições encerradas</h2></a>
			<div class="description">
				<p>As incrições para os projetos ProEneme e ProRedação 2018 foram encerradas hoje, dia 26 de abril. O lista dos incritos selec...</p>
			</div>
			<div class="extra">
				Qui, 24 de abril, 2018
			</div>
		</div>
	</div>
</div>	
<div class="ui pagination menu" style="margin-right: auto; margin-left: auto; width: auto;">
	<a class="active item">
		1
	</a>
	<div class="disabled item">
		...
	</div>
	<a class="item">
		10
	</a>
	<a class="item">
		11
	</a>
	<a class="item">
		12
	</a>
</div>